import { Vector3D } from "../math/index.js";
import { Color } from "../core/colors/index.js";

/**
 * Interface for camera effects that can be applied to a camera.
 * Effects modify the position and target of the camera over time, and may also drive
 * rotation (pitch/yaw) or a post-processing screen flash.
 */
export interface CameraEffect {
  /** The unique type identifier of the effect. */
  readonly type: string;
  /** Whether the effect has finished its duration and should be removed. */
  readonly isFinished: boolean;
  /** The current position offset generated by this effect. */
  readonly offset: Vector3D;
  /** The current target offset generated by this effect. */
  readonly targetOffset: Vector3D;
  /** Pitch (X-axis) rotation offset in radians, applied to the view direction. */
  readonly pitchOffset: number;
  /** Yaw (Y-axis) rotation offset in radians, applied to the view direction. */
  readonly yawOffset: number;
  /** This effect's contribution to the post-processing screen flash, in [0, 1]. */
  readonly flashIntensity: number;
  /** Tint color for this effect's flash contribution. */
  readonly flashColor: Color;

  /**
   * Updates the effect state based on elapsed time.
   * @param deltaTime Time elapsed since the last frame in seconds.
   */
  update(deltaTime: number): void;

  /**
   * Attempts to merge an incoming same-type effect into this one instead of it being added
   * as a separate, independently-decaying instance (e.g. re-triggering Shake accumulates
   * trauma into the already-active instance instead of stacking).
   * @param other The newly requested effect of the same `type`.
   * @returns true if `other` was absorbed into this effect (caller should discard `other`
   * and not add it), false to add `other` as a new, independent effect.
   */
  merge?(other: CameraEffect): boolean;
}
