/// src/core/behaviors/ExternalShaderUniformBehavior.ts
import { Behavior } from "./Behavior.js";
import { Object3D, CustomShaderMaterial } from "../index.js";

/**
 * Automatically feeds external shader uniforms (like iTime, iResolution, or time, resolution)
 * into a CustomShaderMaterial generated by an IShaderImporter (like Shadertoy or GLSLSandbox).
 */
export class ExternalShaderUniformBehavior extends Behavior {
  private _time: number = 0;
  private _resolution: [number, number] = [800, 600];
  private _resolutionVec3: [number, number, number] = [800, 600, 1];

  constructor(resolutionX: number = 800, resolutionY: number = 600) {
    super();
    this._resolution = [resolutionX, resolutionY];
    this._resolutionVec3 = [resolutionX, resolutionY, 1];
  }

  public override update(deltaTime: number): void {
    if (!this.target) return;

    const obj = this.target as Object3D;
    const mat = obj.material;

    if (mat instanceof CustomShaderMaterial) {
      this._time += deltaTime;

      // Shadertoy specific
      mat.setProperty("iTime", this._time);
      mat.setProperty("iTimeDelta", deltaTime);
      mat.setProperty("iResolution", this._resolutionVec3);

      // GLSLSandbox specific
      mat.setProperty("time", this._time);
      mat.setProperty("resolution", this._resolution);
    }
  }
}
