# grobes, benutztes Holz
NORM_STRENGTH="200%"
HEIGHT_BLUR="0x1"
DISP_BLUR="0x3"
SPEC_CONTRAST="0,40%"
ROUGH_GAMMA="1.5"
AO_FINE_BLUR="0x2"
AO_SOFT_BLUR="0x20"
AO_LEVEL="20%,100%"
EDGE_THRESHOLD="85%"
